"""empty message

Revision ID: 11f53f0802ab
Revises: 27c48ab2d99b
Create Date: 2017-01-19 21:13:57.109436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f53f0802ab'
down_revision = '27c48ab2d99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('graph_unit', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'graph_unit')
    # ### end Alembic commands ###
