"""empty message

Revision ID: 27c48ab2d99b
Revises: c5787b1f468b
Create Date: 2017-01-19 20:00:10.749866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c48ab2d99b'
down_revision = 'c5787b1f468b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('rate', sa.Float(), nullable=True))
    op.add_column('service', sa.Column('unit', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'unit')
    op.drop_column('service', 'rate')
    # ### end Alembic commands ###
