"""empty message

Revision ID: 87fe90a91032
Revises: 694f42ac8875
Create Date: 2017-01-02 15:20:04.852684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fe90a91032'
down_revision = '694f42ac8875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('latest_task_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'latest_task_name')
    # ### end Alembic commands ###
