"""empty message

Revision ID: 9e3526047f9f
Revises: 
Create Date: 2017-01-10 16:34:45.431930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3526047f9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Host', 'VM'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('desc'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Host', 'VM'), nullable=False),
    sa.Column('use_self_service', sa.Boolean(), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('hostname', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Enum(u'\u65b0\u52a0\u5165', u'\u914d\u7f6e\u4e2d', u'\u914d\u7f6e\u5b8c\u6210', u'\u914d\u7f6e\u5931\u8d25'), nullable=False),
    sa.Column('latest_task_name', sa.String(length=50), nullable=True),
    sa.Column('vm_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname'),
    sa.UniqueConstraint('ip')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('command', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('physical', 'cloud'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command'),
    sa.UniqueConstraint('name')
    )
    op.create_table('group_machine_map',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'group.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], [u'machine.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'machine_id')
    )
    op.create_table('group_service',
    sa.Column('warn', sa.Integer(), nullable=True),
    sa.Column('critic', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'group.id'], ),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'service_id')
    )
    op.create_table('machine_service',
    sa.Column('warn', sa.Integer(), nullable=True),
    sa.Column('critic', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], [u'machine.id'], ),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ),
    sa.PrimaryKeyConstraint('machine_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_service')
    op.drop_table('group_service')
    op.drop_table('group_machine_map')
    op.drop_table('service')
    op.drop_table('machine')
    op.drop_table('group')
    # ### end Alembic commands ###
