"""empty message

Revision ID: e259e517c2b4
Revises: 9e3526047f9f
Create Date: 2017-01-11 10:39:04.721773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e259e517c2b4'
down_revision = '9e3526047f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('desc', table_name='group')
    op.drop_index('name', table_name='group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'group', ['name'], unique=True)
    op.create_index('desc', 'group', ['desc'], unique=True)
    # ### end Alembic commands ###
