"""empty message

Revision ID: f5ee17fe0046
Revises: 87fe90a91032
Create Date: 2017-01-03 23:09:37.526329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ee17fe0046'
down_revision = '87fe90a91032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=50), nullable=False),
    sa.Column('host_sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('desc'),
    sa.UniqueConstraint('name')
    )
    op.create_table('host_group_service_map',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'host_group.id'], ),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'service_id')
    )
    op.add_column(u'host', sa.Column('host_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'host', 'host_group', ['host_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'host', type_='foreignkey')
    op.drop_column(u'host', 'host_group_id')
    op.drop_table('host_group_service_map')
    op.drop_table('host_group')
    # ### end Alembic commands ###
