"""empty message

Revision ID: fa572e8afdc9
Revises: 17996805fe42
Create Date: 2017-01-01 17:17:09.326476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa572e8afdc9'
down_revision = '17996805fe42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'host', ['ip'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'host', type_='unique')
    # ### end Alembic commands ###
