---
- hosts:
    - monitor_target
  sudo: true
  tasks:
    - name: install ganglia-monitor
      apt:
        name: ganglia-monitor
        update_cache: yes

    - name: change gmond config
      template:
        src: "{{ gmond_src }}"
        dest: "{{ gmond_dest }}"

    - name: restart ganglia-monitor
      service:
        name: ganglia-monitor
        state: restarted
